{{- if .Values.networkPolicies.enabled }}
# Default deny all
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
# Allow Envoy to Frontend
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-envoy-to-frontend
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
---
# Allow Envoy to Auth
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-envoy-to-auth
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.auth.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
      ports:
        - protocol: TCP
          port: {{ .Values.auth.port }}
---
# Allow Envoy to Staff
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-envoy-to-staff
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.staff.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
      ports:
        - protocol: TCP
          port: {{ .Values.staff.port }}
---
# Allow Envoy to Shift
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-envoy-to-shift
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.shift.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
      ports:
        - protocol: TCP
          port: {{ .Values.shift.port }}
---
# Allow Envoy to Leave
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-envoy-to-leave
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.leave.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
      ports:
        - protocol: TCP
          port: {{ .Values.leave.port }}
---
# Frontend Network Policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: medishift-frontend-netpol
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.auth.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.auth.port }}
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.staff.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.staff.port }}
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.shift.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.shift.port }}
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.leave.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.leave.port }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
# Auth Network Policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: medishift-auth-netpol
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.auth.name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.frontend.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.staff.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.shift.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.leave.name }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
      ports:
        - protocol: TCP
          port: {{ .Values.auth.port }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.postgres.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.postgres.port }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
# Staff Network Policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: medishift-staff-netpol
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.staff.name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.frontend.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.auth.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.shift.name }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
      ports:
        - protocol: TCP
          port: {{ .Values.staff.port }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.postgres.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.postgres.port }}
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.auth.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.auth.port }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
# Shift Network Policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: medishift-shift-netpol
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.shift.name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.frontend.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.auth.name }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
      ports:
        - protocol: TCP
          port: {{ .Values.shift.port }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.postgres.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.postgres.port }}
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.auth.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.auth.port }}
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.staff.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.staff.port }}
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.leave.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.leave.port }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
# Leave Network Policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: medishift-leave-netpol
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.leave.name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.frontend.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.auth.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.shift.name }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
      ports:
        - protocol: TCP
          port: {{ .Values.leave.port }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.postgres.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.postgres.port }}
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.auth.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.auth.port }}
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.shift.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.shift.port }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
# Postgres Network Policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: medishift-postgres-netpol
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.auth.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.staff.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.shift.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.leave.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.postgres.port }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}
