apiVersion: v1
kind: Secret
metadata:
  name: medishift-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb }}
