apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medishift-prod
  namespace: argocd
  labels:
    environment: production
    project: medishift
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: default
  source:
    repoURL: https://github.com/MediShift-devops-project/medishift-manifests.git
    targetRevision: main
    path: medishift-helm
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: medishift-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
