apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medishift-dev
  namespace: argocd
  labels:
    environment: development
    project: medishift
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: default
  source:
    repoURL: https://github.com/MediShift-devops-project/medishift-manifests.git
    targetRevision: develop
    path: medishift-helm
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: medishift-dev

  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      name: medishift-postgres-development-pvc
      namespace: medishift-dev
      jsonPointers:
        - /spec/storageClassName
        - /spec/volumeName
        - /spec/volumeMode
        - /status
        - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
        - /metadata/annotations/pv.kubernetes.io~1bind-completed
        - /metadata/finalizers

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
